CREATE DATABASE IF NOT EXISTS `NotebookShop`;

USE `NotebookShop`;

CREATE TABLE IF NOT EXISTS `Notebooks` (
  `id` INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `serial` VARCHAR(100) NOT NULL,
  `vendor` VARCHAR(100) NOT NULL,
  `model` VARCHAR(100) NOT NULL,
  `date` DATE NOT NULL,
  `price` VARCHAR(100) NOT NULL
) ENGINE = InnoDB;

